[build]
  command = "npm install && npm run build"
  functions = "functions"

[context.production]
  environment = { FAUNADB_SECRET="fnAEQ3Rbw2AAw5a8bHoEo1MPhO5Xv-aNyj4ovvOS", API_KEY="WuqquMW7jLeKMy2p" }